import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {AuthenticatorProvider} from "@aws-amplify/ui-react-core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-gray-900" lang="en">
    {/*<AuthenticatorProvider>*/}
      <body className="h-full">{children}</body>
    {/*</AuthenticatorProvider>*/}
    </html>
  );
}
